### ISSUE TITLE
MissingInputException (diffexp.smk, line 1)

### ISSUE THREAD

**Issue by vaalers** [snakemake-workflows/rna-seq-star-deseq2#84]
I am trying to run paired end reads of mouse fastq files. Im not sure how to resolve the error that i keep getting. My config.yml:

```
samples: config/samples.tsv
units: config/units.tsv


ref:
  species: mus_musculus
  release: 102
  build: GRCm38

trimming:
  activate: False

pca:
  activate: True
  labels: ""

diffexp:
  variables_of_interest:
    treatment_1:
      base_level: cSham
    treatment_2:
      base_level: cSham
  batch_effects:
    - jointly_handled
  contrasts:
    treatment_1:
      variable_of_interest: treatment_1
      level_of_interest: cStroke
  model: ""


params:
  cutadapt-pe: ""
  cutadapt-se: ""
  star: ""
```
When I run the workflow I get the following error:
```
$ snakemake --cores 12 --use-conda
Workflow defines that rule get_genome is eligible for caching between workflows (use the --cache argument to enable this).
Workflow defines that rule get_annotation is eligible for caching between workflows (use the --cache argument to enable this).
Workflow defines that rule genome_faidx is eligible for caching between workflows (use the --cache argument to enable this).
Workflow defines that rule bwa_index is eligible for caching between workflows (use the --cache argument to enable this).
Workflow defines that rule star_index is eligible for caching between workflows (use the --cache argument to enable this).
Assuming unrestricted shared filesystem usage.
Building DAG of jobs...
MissingInputException in rule count_matrix in file https://raw.githubusercontent.com/snakemake-workflows/rna-seq-star-deseq2/v2.1.2/workflow/rules/diffexp.smk, line 1:
Missing input files for rule count_matrix:
    output: results/counts/all.tsv
    affected files:
        results/star/Sample12_lane1/ReadsPerGene.out.tab
        results/star/Sample2_lane1/ReadsPerGene.out.tab
        results/star/Sample10_lane1/ReadsPerGene.out.tab
        results/star/Sample4_lane2/ReadsPerGene.out.tab
        results/star/Sample15_lane1/ReadsPerGene.out.tab
        results/star/Sample6_lane1/ReadsPerGene.out.tab
        results/star/Sample13_lane1/ReadsPerGene.out.tab
        results/star/Sample8_lane1/ReadsPerGene.out.tab
        results/star/Sample17_lane1/ReadsPerGene.out.tab
```

Could anyone help me understand how to resolve this issue?
